#
#  Make the Xinu version of the C run-time support library
#
 
CFLAGS  =       -fno-builtin -O -c -I../../h
SFLAGS  =       -I../../h
AR      =       ar
#AR      =       /ugrad0/cs415/GNU/bin/i586-pc-linux-gnu-ar
CC      =       gcc
#CC      =       /ugrad0/cs415/GNU/bin/i586-pc-linux-gnu-gcc
AS      =       as
#AS      =       /ugrad0/cs415/GNU/bin/i586-pc-linux-gnu-as
LIB     =       ..
 
include ./Makefile.lib                                                          
